version: 1.0.{build}

platform:
  - MSYS2

environment:
  PATH: C:\msys64\mingw64\bin;C:\msys64\usr\bin
  CXX: g++

  matrix:
    - _options: ""
    - _options: "--enable-debug-logs --enable-debug-checks"

build_script:
  - bash ci.sh

notifications:

