install:

platform:
  - MSYS2

environment:
  matrix:
    - _options: ""
    - _options: "--enable-debug-logs --enable-debug-checks"

build_script:
  - sh: ${CXX} --version
  - sh: ./check_includes.sh
  - sh: mkdir -p m4
  - sh: autoreconf -ifv
  - sh: ./configure --disable-silent-rules ${_options}
  - sh: make -j$(nproc)

test_script:
  - sh: make -j$(nproc) check || (cat ./test-suite.log; false)

notifications:

