install:

platform:
  - MSYS2

environment:
  matrix:
    - _options: ""
    - _options: "--enable-debug-logs --enable-debug-checks"

build_script:
  - ${CXX} --version
  - ./check_includes.sh
  - mkdir -p m4
  - autoreconf -ifv
  - ./configure --disable-silent-rules ${_options}
  - make -j$(nproc)

test_script:
  - make -j$(nproc) check || (cat ./test-suite.log; false)

notifications:

