platform:
  - MSYS2

environment:
  PATH: C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\Python27;C:\Windows\system32;C:\Windows
  CXX: g++

  matrix:
    - _options: ""
    - _options: "--enable-debug-logs --enable-debug-checks"

build_script:
  - bash ci/build.sh

on_success:
  - python ci/appveyor_irc-notify.py mcfproj "[ lh_mouse {repo_name}#{short_commit}] passed on {branch} by {author} ({build_url})"

on_failure:
  - python ci/appveyor_irc-notify.py mcfproj "[ lh_mouse {repo_name}#{short_commit}] errored on {branch} by {author} ({build_url})"
