matrix:
  arch:
    - 64
    - 32
  _options:
    - ""
    - "--enable-debug-{logs,checks}"

build:
  image: teaci/msys$${arch}
  pull: true
  shell: mingw$${arch}
  commands:
    - mkdir -p m4
    - autoreconf -ifv
    - ./configure --disable-werror --disable-silent-rules $${_options}
    - make -j$(nproc)
    - ./check_includes.sh
    - make -j$(nproc) check

notify:
  irc:
    prefix: " lh_mouse"
    nick: tea-ci
    channel: mcfproj
    server:
      host: chat.freenode.net
      port: 6697
      tls: true
