matrix:
  arch:
    - 64
    - 32
  _options:
    - ""
    - "--enable-debug-logs --enable-debug-checks"

build:
  image: teaci/msys$${arch}
  pull: true
  shell: mingw$${arch}
  commands:
    - g++ --version
    - ./check_includes.sh
    - mkdir -p m4
    - autoreconf -ifv
    - ./configure --disable-silent-rules $${_options}
    - make -j$(nproc) check || (cat ./test-suite.log; false)

notify:
  irc:
    prefix: " lh_mouse"
    nick: tea-ci
    channel: mcfproj
    server:
      host: chat.freenode.net
      port: 6697
      tls: true
