language: cpp

os: linux
dist: xenial
sudo: required

addons:
  apt:
    update: true
    packages:
      - checkinstall

env:
  - _options=""
  - _options="--enable-debug-logs --enable-debug-checks"

compiler:
  - gcc
  - clang

install:
  - ${CXX} --version
  - ./check_includes.sh
  - mkdir -p m4
  - autoreconf -ifv
  - test "${CXX#g++}" == "${CXX}" || _options+=" CPPFLAGS=-Werror"
  - ./configure --disable-silent-rules ${_options}
  - make -j$(nproc) check

script:
  - exit 0

notifications:
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/#mcfproj"
    template:
      - "[ lh_mouse %{repository_slug}#%{commit}] %{result} on %{branch} by %{author} (%{build_url})"
  email: false
