language: cpp

os: linux
dist: trusty
sudo: required

addons:
  apt:
    packages:
      - checkinstall

matrix:
  include:
    - env: "_options=\"--enable-debug-logs\""
    - env: "_options=\"\""

install:
  - "mkdir -p m4"
  - "autoreconf -ifv"
  - "./configure CPPFLAGS=\"-D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC\" CXXFLAGS=\"-O1\" ${_options}"
  - "make -j$(nproc)"

script:
  - "./makedeb.sh"
  - "./bin/asteria </dev/null"
  - "CPPFLAGS=\"-D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC\" ./run_tests.sh"
  # Make sure that all `#include` directives in our headers are met.
  - |
    _cmd="${CXX} -x c++ -std=c++11"
    echo "Checking #include directives using command:" ${_cmd}
    ${_cmd} -Wall -Wextra -Werror $(find src -name "*.hpp") -c /dev/null

notifications:
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/#mcfproj"
    template:
      - "[ lh_mouse %{repository_slug}#%{commit}] %{result} on %{branch} by %{author} (%{build_url})"
  email: false
