language: cpp

os: linux
dist: xenial
sudo: required

env:
  - _options=""
  - _options="--enable-debug-logs --enable-debug-checks"

compiler:
  - gcc
  - clang

install:
  - ./ci.sh

notifications:
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/#mcfproj"
    template:
      - "[ lh_mouse %{repository_slug}#%{commit}] %{result} on %{branch} by %{author} (%{build_url})"
  email: false
